openai:
  llm_model: gpt-4o
  tts_model: gpt-4o-mini-tts
  default_voice: ash

deepgram:
  model: nova-2-general
  language: en-US
  sample_rate: 16000   # use 16000 if your source is telephony
  stt:
    interim_results: true
    no_delay: true
    endpointing_ms: 60
    punctuate: false
    smart_format: false
    filler_words: false
    numerals: false


voices:
  router:
    provider: openai
    model: gpt-4o-mini-tts
    voice: alloy
  booking:
    provider: openai
    model: gpt-4o-mini-tts
    voice: verse
  reschedule:
    provider: openai
    model: gpt-4o-mini-tts
    voice: sage
  cancel:
    provider: openai
    model: gpt-4o-mini-tts
    voice: breeze
  parts:
    provider: openai
    model: gpt-4o-mini-tts
    voice: opal
  status:
    provider: openai
    model: gpt-4o-mini-tts
    voice: pearl
  pricing:
    provider: openai
    model: gpt-4o-mini-tts
    voice: aria
  billing:
    provider: openai
    model: gpt-4o-mini-tts
    voice: lyra
  operator:
    provider: openai
    model: gpt-4o-mini-tts
    voice: nala
