services:
  db:
    image: postgres:16
    container_name: plumber-pg
    environment:
      POSTGRES_USER: plumber
      POSTGRES_PASSWORD: plumber
      POSTGRES_DB: plumbing
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plumber -d plumbing || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      DATABASE_URL: postgresql+asyncpg://plumber:plumber@db:5432/plumbing?ssl=false
    ports:
      - "8000:8000"
    command: ["uv", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

# declare named volumes at the end of the file
volumes:
  pgdata:
